import { useMemo } from 'react';
import { Icon } from '../../components/Icon';
import type { Requirement, RequirementFolder } from '../../lib/types';

export function FolderOverview({ folders, requirements, query, canEdit, onSelect, onOpenRequirements, onCreateFolder, onCreateRequirement, onSettings }: { folders: RequirementFolder[]; requirements: Requirement[]; query: string; canEdit: boolean; onSelect: (id: string) => void; onOpenRequirements: () => void; onCreateFolder: () => void; onCreateRequirement: () => void; onSettings: () => void }) {
  const normalized = query.trim().toLocaleLowerCase('pt-BR');
  const visible = useMemo(() => requirements.filter((item) => !normalized || `${item.code} ${item.title}`.toLocaleLowerCase('pt-BR').includes(normalized)), [normalized, requirements]);
  const visibleFolders = useMemo(() => folders.filter((folder) => folder.name !== 'Sem pasta' || visible.some((item) => item.folderId === folder.id)), [folders, visible]);
  return <section className="folder-overview"><header className="folder-overview-heading"><div><p className="section-kicker">Organização do projeto</p><h1>{normalized ? `Resultados para “${query}”` : 'Requisitos organizados por pasta'}</h1><p>{normalized ? `${visible.length} User Stories encontradas` : 'Selecione uma User Story para revelar sua rede de dependências.'}</p></div><div className="overview-metrics">{canEdit && <><button className="secondary-button project-create-folder" onClick={onCreateFolder}><Icon name="folder" size={14}/> Nova pasta</button><button className="primary-button project-create-requirement" onClick={onCreateRequirement}><Icon name="plus" size={15}/> Novo requisito</button></>}<button className="project-requirements-link" onClick={onOpenRequirements}><Icon name="list" size={14}/> Requisitos <span>{visible.length}</span></button><span><Icon name="folder" size={13}/> {visibleFolders.length} pastas</span><button className="overview-settings" onClick={onSettings} aria-label="Abrir configurações do projeto" title="Configurações do projeto"><Icon name="settings" size={14}/></button></div></header><div className="folder-grid">{visibleFolders.map((folder) => { const items = visible.filter((item) => item.folderId === folder.id); return <section className="folder-card" key={folder.id}><header><span className="folder-icon"><Icon name="folder" size={16}/></span><div><h2>{folder.name}</h2><p>{folder.description || 'User Stories deste grupo'}</p></div><span className="folder-count">{items.length} US</span></header><div className="folder-requirements">{items.length ? items.map((item) => <button key={item.id} onClick={() => onSelect(item.id)}><span className="us-type">US</span><span className="us-name">{item.title}</span><span className="us-relations"><Icon name="branch" size={11}/> {item.status === 'ARCHIVED' ? 'Cancelada' : 'Abrir grafo'}</span></button>) : <div className="folder-card-empty"><Icon name="folder" size={18}/><span>Nenhuma US nesta pasta</span></div>}</div></section>; })}</div>{!visibleFolders.length && <div className="folder-empty"><Icon name="folder" size={24}/><strong>{normalized ? 'Nenhuma pasta encontrada' : 'Nenhuma pasta criada'}</strong><span>{normalized ? 'Tente buscar por outro termo.' : 'Crie uma pasta pelo botão no topo para organizar suas US.'}</span></div>}{Boolean(visibleFolders.length && !visible.length) && <div className="folder-empty"><Icon name="search" size={24}/><strong>Nenhuma US encontrada</strong><span>Tente buscar por outro termo.</span></div>}</section>;
}
