// @vitest-environment jsdom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { api } from '../../lib/api';
import { IntegrationCandidatesPanel } from './IntegrationCandidatesPanel';

vi.mock('../../lib/api', async original => ({ ...await original<typeof import('../../lib/api')>(), api: vi.fn() }));
let host: HTMLDivElement; let root: Root; let client: QueryClient; let mode: 'ok' | 'empty' | 'error' | 'mixed';
const run = { id: 'run-1', status: 'COMPLETED', startedAt: '2026-09-12T12:00:00.000Z', completedAt: '2026-09-12T12:01:00.000Z', scannedCount: 31, changedCount: 2, itemCount: 2, folder: { id: 'folder-1', name: 'Produto', project: { id: 'p1', key: 'ATH', name: 'ATHENA' } } } as const;
const item = { id: 'item-1', title: 'Requisito importado', externalId: 'google:drive:1', changeType: 'UPDATED', createdAt: '2026-09-12T12:00:10.000Z', candidate: { status: 'ACCEPTED', content: { content: 'Texto externo' }, previousContent: { content: 'Texto anterior' }, previousTitle: 'Título anterior', updatedAt: '2026-09-12T12:00:10.000Z' } } as const;
beforeEach(() => { mode = 'ok'; vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true); vi.mocked(api).mockImplementation(async path => { const url=String(path); if (url.includes('/integrations/activity?')) { if (mode === 'error') throw new Error('Falha temporária'); if (mode === 'empty') return { items: [], nextCursor: null } as never; const drive={ id: 'GOOGLE_SYNC:run-1', source: 'GOOGLE_SYNC', provider: 'GOOGLE', action: 'SYNC', status: 'COMPLETED', occurredAt: run.startedAt, title: run.folder.name, summary: '2 alterações · 31 arquivos lidos', detailId: run.id, itemCount: 2, scannedCount: 31, changedCount: 2 }; const github={ id:'ACTIVITY:g1',source:'ACTIVITY',provider:'GITHUB',action:'TASK_CREATED',status:'COMPLETED',occurredAt:'2026-09-13T12:00:00.000Z',title:'Issue nova',summary:'Tarefa criada pelo ATHENA',url:'https://github.com/equipe/repo/issues/2' }; const openproject={ id:'ACTIVITY:o1',source:'ACTIVITY',provider:'OPENPROJECT',action:'TASK_LINKED',status:'COMPLETED',occurredAt:'2026-09-14T12:00:00.000Z',title:'Pacote de trabalho',summary:'Tarefa vinculada ao ATHENA' }; const all=mode==='mixed'?[drive,github,openproject]:[drive]; return {items:url.includes('provider=GITHUB')?all.filter((entry:any)=>entry.provider==='GITHUB'):all,nextCursor:null} as never; } if (url === '/workspaces/w1/integrations/google/sync-runs/run-1/items') return { items: [item], nextCursor: 'next' } as never; if (url.includes('cursor=next')) return { items: [], nextCursor: null } as never; return [] as never; }); host = document.createElement('div'); document.body.append(host); root = createRoot(host); client = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: Infinity } } }); });
afterEach(() => { act(() => root.unmount()); client.clear(); host.remove(); window.history.replaceState({}, '', '/'); vi.unstubAllGlobals(); });
async function mount(role:'OWNER'|'VIEWER'='VIEWER') { await act(async () => root.render(<QueryClientProvider client={client}><IntegrationCandidatesPanel workspaceId="w1" projectId="p1" role={role}/></QueryClientProvider>)); await act(async () => { await new Promise(resolve => setTimeout(resolve, 0)); }); }
async function openActivityTab() { const tab=host.querySelector<HTMLButtonElement>('#integrations-tab-activity')!; await act(async()=>tab.click()); await act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));}); }
describe('IntegrationCandidatesPanel', () => {
  it('organiza a página em abas e move o foco com as setas', async () => { await mount(); const tabs=[...host.querySelectorAll<HTMLButtonElement>('[role="tab"]')]; expect(tabs.map(tab=>tab.textContent)).toEqual(['Tarefas externas','Armazenamento','Histórico de integrações']); expect(tabs[0].getAttribute('aria-selected')).toBe('true'); await act(async()=>tabs[0].dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}))); expect(tabs[1].getAttribute('aria-selected')).toBe('true'); expect(document.activeElement).toBe(tabs[1]); });
  it('abre o Google Drive depois do retorno OAuth', async () => { window.history.replaceState({},'', '/?integration=google&status=connected&workspaceId=w1'); await mount('OWNER'); expect(host.querySelector('#integrations-tab-drive')?.getAttribute('aria-selected')).toBe('true'); expect(host.textContent).toContain('Google Drive conectado. Agora escolha uma pasta para iniciar a sincronização.'); });
  it('mantém credenciais digitadas ao alternar as abas', async () => { await mount('OWNER'); const input=host.querySelector<HTMLInputElement>('input[placeholder="ghp_…"]')!; await act(async()=>{const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!;setter.call(input,'ghp_teste');input.dispatchEvent(new Event('input',{bubbles:true}));}); expect(input.value).toBe('ghp_teste'); await act(async()=>host.querySelector<HTMLButtonElement>('#integrations-tab-drive')!.click()); await act(async()=>host.querySelector<HTMLButtonElement>('#integrations-tab-tasks')!.click()); expect(host.querySelector<HTMLInputElement>('input[placeholder="ghp_…"]')?.value).toBe('ghp_teste'); });
  it('mistura o histórico e carrega detalhes da sincronização ao expandir', async () => { await mount(); await openActivityTab(); expect(host.textContent).toContain('Produto'); expect(host.textContent).not.toContain('Texto externo'); const trigger = host.querySelector<HTMLButtonElement>('.integration-history-trigger')!; expect(trigger.getAttribute('aria-expanded')).toBe('false'); await act(async () => trigger.click()); await act(async () => { await new Promise(resolve => setTimeout(resolve, 0)); }); expect(trigger.getAttribute('aria-expanded')).toBe('true'); expect(host.textContent).toContain('Texto externo'); expect(host.textContent).toContain('Carregar mais documentos'); });
  it('mostra erro e permite tentar novamente', async () => { mode = 'error'; await mount(); await openActivityTab(); expect(host.textContent).toContain('Falha temporária'); mode = 'ok'; const retry = [...host.querySelectorAll<HTMLButtonElement>('button')].find(button => button.textContent === 'Tentar novamente')!; await act(async () => retry.click()); await act(async () => { await new Promise(resolve => setTimeout(resolve, 0)); }); expect(host.textContent).toContain('Produto'); });
  it('mostra a mensagem vazia quando ainda não há eventos de integração', async () => { mode = 'empty'; await mount(); await openActivityTab(); expect(host.textContent).toContain('Sem atividade por enquanto'); expect(host.textContent).toContain('As sincronizações do Drive e as tarefas criadas ou vinculadas pelo ATHENA aparecerão aqui.'); });
  it('exibe Drive, GitHub e OpenProject e filtra por integração', async () => { mode='mixed'; await mount(); await openActivityTab(); expect(host.textContent).toContain('Issue nova'); expect(host.textContent).toContain('Pacote de trabalho'); await act(async()=>[...host.querySelectorAll<HTMLButtonElement>('.integration-history-filters button')].find(button=>button.textContent==='GitHub')!.click()); await act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));}); expect(host.textContent).toContain('Issue nova'); expect(host.textContent).not.toContain('Pacote de trabalho'); });
  it('filtra o histórico por status e intervalo personalizado', async () => {
    await mount(); await openActivityTab();
    const setValue = (element: HTMLInputElement | HTMLSelectElement, value: string) => {
      const setter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(element), 'value')!.set!;
      setter.call(element, value);
      element.dispatchEvent(new Event(element instanceof HTMLSelectElement ? 'change' : 'input', { bubbles: true }));
    };
    await act(async () => setValue(host.querySelector<HTMLSelectElement>('select[aria-label="Filtrar por período"]')!, 'CUSTOM'));
    await act(async () => {
      setValue(host.querySelector<HTMLInputElement>('input[aria-label="Data inicial"]')!, '2026-09-10');
      setValue(host.querySelector<HTMLInputElement>('input[aria-label="Data final"]')!, '2026-09-12');
      setValue(host.querySelector<HTMLSelectElement>('select[aria-label="Filtrar por status"]')!, 'FAILED');
      await new Promise(resolve => setTimeout(resolve, 0));
    });
    const request = vi.mocked(api).mock.calls.map(([path]) => new URL(String(path), 'http://localhost')).find(url => url.searchParams.get('status') === 'FAILED' && url.searchParams.has('from') && url.searchParams.has('to'));
    expect(request?.searchParams.get('from')).toBe(new Date(2026, 8, 10).toISOString());
    expect(request?.searchParams.get('to')).toBe(new Date(2026, 8, 13).toISOString());
  });
});
